# Generated by Django 3.1 on 2020-09-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200901_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Главная фотка'),
        ),
    ]
