# Generated by Django 3.1 on 2020-09-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200905_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='adverted',
            field=models.BooleanField(default=False, verbose_name='Is adverted'),
        ),
    ]
