# Generated by Django 3.1 on 2020-09-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_car_adverted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Механика', 'Mechanics'), ('Автомат', 'Auto')], default='M', max_length=10, verbose_name='КПП'),
        ),
    ]
