# Generated by Django 3.1 on 2020-09-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_car_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-date_publication']},
        ),
    ]
