# Generated by Django 3.1 on 2020-09-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20200910_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Опубликовано'),
        ),
    ]
