# Generated by Django 3.1 on 2020-09-11 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0012_auto_20200910_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='cStatus',
        ),
        migrations.AddField(
            model_name='car',
            name='user_create',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(default='Харьков', max_length=150, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='contact',
            field=phone_field.models.PhoneField(max_length=31, verbose_name='Контактный номер'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('Дизель', 'Дизель'), ('Бензин', 'Бензин'), ('Газ', 'Газ')], default='Бензин', max_length=100, verbose_name='Тип Движка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Механика', 'Механика'), ('Автомат', 'Автомат')], default='M', max_length=10, verbose_name='Коробка Передач'),
        ),
    ]
