# Generated by Django 3.1.1 on 2020-09-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20200911_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='img',
            field=models.ImageField(max_length=255, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Главная фотка'),
        ),
    ]
