# Generated by Django 3.1 on 2020-09-27 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200917_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='contact',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Неверный формат', regex='^\\+(?:[0-9]●?){6,14}[0-9]$')], verbose_name='Номер телефона'),
        ),
    ]
