# Generated by Django 3.1 on 2020-10-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20201019_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
