# Generated by Django 3.1 on 2020-10-20 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20201019_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='carTitle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.cartype', verbose_name='Название'),
        ),
    ]
