# Generated by Django 3.1 on 2020-10-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_carimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carimage',
            old_name='post',
            new_name='car',
        ),
    ]
