# Generated by Django 3.1 on 2020-10-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_order_order_item_ship_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_item',
            old_name='car',
            new_name='product',
        ),
    ]
