# Generated by Django 3.1 on 2020-11-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_auto_20201031_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='digital',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
