# Generated by Django 3.1 on 2020-11-11 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_car_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship_adress',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='ship_adress',
            name='first_name',
            field=models.CharField(default='booki', max_length=200),
        ),
        migrations.AddField(
            model_name='ship_adress',
            name='last_name',
            field=models.CharField(default='dwwe', max_length=200),
        ),
        migrations.AddField(
            model_name='ship_adress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Неверный формат', regex='^\\+(?:[0-9]●?){6,14}[0-9]$')], verbose_name='Номер телефона'),
        ),
    ]
