# Generated by Django 3.1 on 2020-11-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_auto_20201111_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship_adress',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ship_adress',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
    ]
